export default {
  ucbgTaxonTermTypes: {
    values: [
      'Verified Taxonomic Name',
      'Taxon No Author Name',
      'Unverified Name',
      'Grex Name',
    ],
  },
  taxonTermSources: {
    values: [
      'Royal Botanical Gardens (KEW)',
      'Owner, Database',
      'UC Botanical Garden',
    ],
  },
  ucbgTaxonomicStatuses: {
    values: [
      'valid',
      'invalid',
      'misapplied',
      'accepted',
      'synonym',
      'illegitimate',
      'unpublished',
    ],
  },
  taxonAuthorTypes: {
    values: [
      'author',
      'ascribed author',
      'parenthetical author',
      'parenthetical ascribed author',
    ],
  },
  ucbgTaxonRanks: {
    values: [
      'unknown',
      'class',
      'cultivar',
      'division',
      'family',
      'form',
      'genus',
      'grex',
      'group',
      'kingdom',
      'nothomorph',
      'order',
      'proles',
      'race',
      'section',
      'series',
      'species',
      'subclass',
      'subdivision',
      'subfamily',
      'subform',
      'subgenus',
      'subkingdom',
      'suborder',
      'subsection',
      'subseries',
      'subspecies',
      'subtribe',
      'subvariety',
      'tribe',
      'variety',
    ],
  },
};
